### DISCUSSION TITLE
Behaviour of CAPI KamajiControlPlane provider when no infrastructure is used

### DISCUSSION THREAD

**Discussion by joseluisgonzalezca** [clastix/cluster-api-control-plane-provider-kamaji#174] [Q&A] [answered]
Hello everyone!

As I stated in this discussion, https://github.com/clastix/cluster-api-control-plane-provider-kamaji/discussions/88#discussioncomment-12419428, I’m trying to understand how CAPI works and the building blocks that compose it while using Kamaji provider.

My idea is to use the CAPI operator to create a Kamaji control plane. I’m going to leave the infrastructure part empty because I want to manage the workers independently. 

In my management cluster, I installed the CAPI operator using Helm and then installed the provider using this YAML manifest:

```yaml
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: kamaji
  namespace: capi-operator-system
spec:
  manager:
    featureGates:
      SkipInfraClusterPatch: true
```

It’s important to highlight the fact that I used the feature gate to be able to deploy the control plane without the obligation to specify an infrastructure provider (see PR #147). Once that part is working correctly, I created a `Cluster` resource that uses a `KamajiControlPlane` resource as a reference for the control plane. Here’s the example manifest:

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test-kamaji
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: KamajiControlPlane
    name: test-kamaji-control-plane
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
  name: test-kamaji-control-plane
  namespace: default
spec:
  addons:
    coreDNS: {}
  controlPlaneEndpoint:
    host: 172.22.3.30
    port: 6443
  dataStoreName: default
  kubelet:
    cgroupfs: systemd
    preferredAddressTypes:
    - InternalIP
  network:
    serviceType: ClusterIP
  replicas: 3
  version: 1.30.0
```

As far as I understand, once the KamajiControlPlane is deployed, `Cluster` resource should be marked as Provisioned because no infra is required. However, it's stuck at Provisioning state because of this:

```
capiv1beta1.Cluster Control Plane endpoint still unprocessed, enqueuing back
``` 

As the feature gate is enabled, `Cluster` resource is not patched accordingly and this error is received. If I configure `controlPlaneEndpoint` param in the `Cluster` resource instead of in the `KamajiControlPlane` resource, `Cluster` state is updated correctly to `Provisioned`.

After seeing that, I don't see benefit of PR #137. What problem does solve including `spec.controlPlaneEndpoint` parameter in `KamajiControlPlane` resource?

Sorry for my ignorance. I just started learning about CAPI and some of the concepts are a little bit confusing for me.

Thanks for your help and time!
