### ISSUE TITLE
Ability to specify additionalMetadata: labels and annotations for pods

### ISSUE THREAD

**Issue by kvaps** [clastix/cluster-api-control-plane-provider-kamaji#157]
It seems there is no oportunity to specify extra labels and annotations for the pods created by TCP

**Comment by kvaps** [comment]
My bad, it is possible using:

```yaml
spec:
  deployment:
    podAdditionalMetadata:
```
