### ISSUE TITLE
[BUG] panic while reconciling Kamaji Control Plane

### ISSUE THREAD

**Issue by shanduur** [clastix/cluster-api-control-plane-provider-kamaji#165]
As in the title - I am seeing panic in CACPP-Kamaji that occurs when I am creating new test cluster:

### Components

```
NAME                   NAMESPACE                       TYPE                   CURRENT VERSION   NEXT VERSION
bootstrap-kubeadm      capi-kubeadm-bootstrap-system   BootstrapProvider      v1.9.4            Already up to date
control-plane-kamaji   kamaji-system                   ControlPlaneProvider   v0.13.0           Already up to date
cluster-api            capi-system                     CoreProvider           v1.9.4            Already up to date
```

### Cluster

<details>
<summary>Cluster Configuration</summary>

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test
  namespace: default
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: KamajiControlPlane
    name: test
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KinkCluster
    name: test
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: test
  namespace: default
spec:
  clusterName: test
  replicas: 1
  selector:
    matchLabels: {}
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: test
      clusterName: test
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
        kind: KinkMachineTemplate
        name: test
      version: 1.31.0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: test
  namespace: default
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KinkCluster
metadata:
  name: test
  namespace: default
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
  name: test
  namespace: default
spec:
  version: 1.31.0
  dataStoreName: default
  deployment:
  replicas: 2
  addons:
    coreDNS: {}
    kubeProxy: {}
  kubelet:
    cgroupfs: systemd
    preferredAddressTypes:
    - InternalIP
  network:
    serviceType: LoadBalancer
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KinkMachineTemplate
metadata:
  name: test
  namespace: default
spec:
  template:
    spec: {}
```

</details>

### Logs

- [cacpp-kamaji.log](https://github.com/user-attachments/files/18517337/cacpp-kamaji.log)

**Comment by prometherion** [comment]
This is the root cause:

https://github.com/clastix/cluster-api-control-plane-provider-kamaji/blob/0278ce2432514050ef14293612d8b2d09d10e6a2/controllers/kamajicontrolplane_controller_tcp.go#L62-L66

You can easily fix it now by defining the `ClusterNetwork` field in your `Cluster` resource, such as:
```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test
  namespace: default
spec:
  clusterNetwork:
    apiServerPort: 443
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: KamajiControlPlane
    name: test
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: KinkCluster
    name: test
```

In the meanwhile, I'll work to avoid this kind of nil pointer dereference since `clusterNetwork` seems optional and I didn't think of it.
