### ISSUE TITLE
Missing list and watch permissions on vsphereclusters and other resources

### ISSUE THREAD

**Issue by bsctl** [clastix/cluster-api-control-plane-provider-kamaji#169]
Missing `list` and `watch` permissions on vsphereclusters and other resources

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    cluster.x-k8s.io/provider: kamaji
  name: capi-kamaji-manager-role
rules:
- apiGroups:
  - infrastructure.cluster.x-k8s.io
  resources:
  - proxmoxclusters
  - tinkerbellclusters
  - vsphereclusters
  verbs:
  - get
  - patch
```
