### ISSUE TITLE
KamajiControlPlane Not Processed by Kamaji on NodePort Configuration

### ISSUE THREAD

**Issue by febri4n** [clastix/cluster-api-control-plane-provider-kamaji#217]
I’m encountering the same error as described in this issue ([link](https://github.com/clastix/cluster-api-control-plane-provider-kamaji/issues/212)).
I'm already using the latest version. In this case, I'm trying to use Kamaji Cluster API with NodePort.
```yaml
Status:
  Conditions:
    Last Transition Time:          2025-05-23T02:17:36Z
    Message:                       
    Observed Generation:           1
    Reason:                        Succeeded
    Status:                        True
    Type:                          TenantControlPlaneCreated
    Last Transition Time:          2025-05-23T02:17:36Z
    Message:                       Control Plane Endpoint is not yet available since unprocessed by Kamaji
    Observed Generation:           1
    Reason:                        Pending
    Status:                        False
    Type:                          TenantControlPlaneAddressReady
```
```bash
clusterctl upgrade plan | grep kamaji
Checking new release availability...
control-plane-kamaji       kamaji-system                       ControlPlaneProvider     v0.15.2           Already up to date
```
This is the YAML configuration
```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
  name: nodeport-capi-kamaji
  namespace: default
spec:
  replicas: 3
  version: 1.30.2
  dataStoreName: kamaji-etcd
  addons:
    coreDNS: {}
    kubeProxy: {}
    konnectivity:
      server:
        port: 31132
  kubelet:
    preferredAddressTypes:
      - InternalIP
      - ExternalIP
      - Hostname
  controlPlaneEndpoint:
    host: xx.xx.xx.xx
    port: 31443
  network:
    serviceType: NodePort
    serviceAddress: xx.xx.xx.xx
    certSANs:
    - xx.xx.xx.xx
  controllerManager:
    extraArgs:
    - --cloud-provider=external
  apiServer:
    extraArgs:
    - --cloud-provider=external
```

**Comment by prometherion** [comment]
Is that port (`31443`) in the valid Node Port range?

I would suggest checking Kamaji logs: it contains the reason why Service isn't created and unprocessed.

**Comment by febri4n** [comment]
Isn't 31443 a valid port within the NodePort range?

Below is the log:
```bash
2025-05-23T02:55:37Z    ERROR   Reconciler error        {"controller": "tenantcontrolplane", "controllerGroup": "kamaji.clastix.io", "controllerKind": "TenantControlPlane", "TenantControlPlane": {"name":"nodeport-capi-kamaji","namespace":"default"}, "namespace": "default", "name": "nodeport-capi-kamaji", "reconcileID": "6491c9c4-0327-4fb6-9f91-3fff520174d4", "error": "Service \"nodeport-capi-kamaji\" is invalid: spec.ports[0].nodePort: Invalid value: 6443: provided port is not in the valid range. The range of valid ports is 30000-32767"}
```

**Comment by febri4n** [comment]
I also tried adding it to the Cluster object, as shown in the YAML below, but Kamaji still doesn't process it.

```yaml
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: nodeport-capi-kamaji
  namespace: default
spec:
  controlPlaneEndpoint:
    host: xx.xx.xx.xx
    port: 31443
  clusterNetwork:
    serviceDomain: cluster.local
    pods:
      cidrBlocks:
      - 10.244.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: KamajiControlPlane
    name: nodeport-capi-kamaji
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OpenStackCluster
    name: nodeport-capi-kamaji
```
