### ISSUE TITLE
CAPI ClusterClass support

### ISSUE THREAD

**Issue by vriabyk** [clastix/cluster-api-control-plane-provider-kamaji#220]
Hello!

I am looking into ClusterClass (ClusterTopology) feature of CAPI:

https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-class/

and trying to use it with Kamaji, Kubevirt and Kubeadm providers. I use the following manifest for tests:
```
apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: quick-start
spec:
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
      kind: KamajiControlPlaneTemplate
      name: quick-start-control-plane
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
      kind: KubevirtClusterTemplate
      name: quick-start-cluster
  workers:
    machineDeployments:
    - class: default-worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: quick-start-default-worker-bootstraptemplate
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
            kind: KubevirtMachineTemplate
            name: quick-start-default-worker-machinetemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtClusterTemplate
metadata:
  name: quick-start-cluster
  annotations:
    cluster.x-k8s.io/managed-by: kamaji
spec:
  template:
    spec: {}
---
kind: KamajiControlPlaneTemplate
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
metadata:
  name: quick-start-control-plane
spec:
  template:
    spec:
      dataStoreName: default
      addons:
        coreDNS: {}
        konnectivity: {}
      kubelet:
        cgroupfs: systemd
        preferredAddressTypes:
        - InternalIP
        - ExternalIP
      network:
        serviceType: LoadBalancer
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: KubevirtMachineTemplate
metadata:
  name: quick-start-default-worker-machinetemplate
spec:
  template:
    spec:
      virtualMachineBootstrapCheck:
        checkStrategy: ssh
      virtualMachineTemplate:
        metadata:
          namespace: default
        spec:
          runStrategy: Always
          template:
            spec:
              domain:
                cpu:
                  cores: 2
                devices:
                  disks:
                  - disk:
                      bus: virtio
                    name: containervolume
                  networkInterfaceMultiqueue: true
                memory:
                  guest: 4Gi
              evictionStrategy: External
              volumes:
              - containerDisk:
                  image: quay.io/capk/ubuntu-2404-container-disk:v1.32.1
                name: containervolume
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: quick-start-default-worker-bootstraptemplate
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration: {} # node registration parameters are automatically injected by CAPD according to the kindest/node image in use.
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: quick-start
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.36.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/16
  topology:
    class: quick-start
    version: v1.32.1
    controlPlane:
      replicas: 3
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 3
```

It creates objects successfully, provisions controlPlane part, MachineDeployment and Kubevirt VMs. However worker VMs can't register into new k8s cluster. I found that this setup creates two k8s services at mgmt cluster:
```
quick-start-kkw75   LoadBalancer   172.16.61.184   10.128.18.204   6443:31440/TCP,8132:30720/TCP   3m52s   kamaji.clastix.io/component=service,kamaji.clastix.io/name=quick-start-kkw75,kamaji.clastix.io/project=kamaji
quick-start-lb      ClusterIP      172.16.27.144   <none>          6443/TCP                        3m53s   cluster.x-k8s.io/cluster-name=quick-start
```
even despite I specify kamaji`s annotation in KubevirtClusterTemplate. I think this causes KubeadmConfig objects to receive incorrect `apiServerEndpoint`:
```
  joinConfiguration:
    discovery:
      bootstrapToken:
        apiServerEndpoint: 172.16.27.144:6443
```
while it should point to `10.128.18.204` created by Kamaji.

Am I missing smth? Maybe there is some known issue. Any help will be much appreciated.

I use the following provider versions:
```
bootstrap: "cluster-api-kubeadm:kubeadm:v1.9.6"
core: "cluster-api-system:cluster-api:v1.9.6"
controlPlane: "cluster-api-kamaji:kamaji:v0.14.2"
infrastructure: "cluster-api-kubevirt:kubevirt:v0.1.10"
```
and deploy CAPI operator with providers using helm chart.
