### ISSUE TITLE
Support for Ingress in KamajiControlPlane spec

### ISSUE THREAD

**Issue by fchiacchiaretta** [clastix/cluster-api-control-plane-provider-kamaji#42]
Matching `ingress` support in  `kamaji.clastix.io/v1alpha1 TenantControlPlane` spec, it would be useful to have `ingress` support also on `controlplane.cluster.x-k8s.io/v1alpha1 KamajiControlPlane`.

A suggested schema could be the following as discussed

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
spec:
  network:
    ingress:
      className:
      hostname:
      extraLabels:
      extraAnnotations:
```
