### ISSUE TITLE
KamajiControlPlane transient error results in cluster.x-k8s.io Cluster permanent `phase: Failed`

### ISSUE THREAD

**Issue by fchiacchiaretta** [clastix/cluster-api-control-plane-provider-kamaji#52]
When `KamajiControlPlane` experience a transient `Failure` (i.e. cannot patch OpenStack Cluster resource), capi-controller manager watches for referenced `KamajiControlPlane` object, detect the `Failure` and set `Failure` and `FailureMessage` from `KamajiControlPlane` in `Cluster` resources, setting `phase: Failed` and treating `Cluster` as in unrecoverable error state.

```yaml
status:
  conditions:
  - lastTransitionTime: "2023-09-05T14:09:55Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-09-04T10:17:28Z"
    status: "True"
    type: ControlPlaneInitialized
  - lastTransitionTime: "2023-09-05T14:09:55Z"
    status: "True"
    type: ControlPlaneReady
  - lastTransitionTime: "2023-09-04T10:17:27Z"
    status: "True"
    type: InfrastructureReady
  controlPlaneReady: true
  failureDomains:
    nova:
      controlPlane: true
  failureMessage: 'Failure detected from referenced resource controlplane.cluster.x-k8s.io/v1alpha1,
    Kind=KamajiControlPlane with name "my-cluster":
    cannot perform PATCH update for the OpenStackCluster resource: Internal error
    occurred: error resolving resource'
  failureReason: PatchCluster
  infrastructureReady: true
  observedGeneration: 3
  phase: Failed
```

Even if `KamajiControlPlane` recovers, `Cluster` is left in `phase: Failed`.
