### ISSUE TITLE
coreDNS is not deployed when specified as an empty dict in KamajiControlPlane

### ISSUE THREAD

**Issue by fchiacchiaretta** [clastix/cluster-api-control-plane-provider-kamaji#61]
When applying this `KamajiControlPlane`, coreDNS is not deployed in managed cluster

```yaml
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: KamajiControlPlane
metadata:
  name: my-cluster
  namespace: my-namespace
spec:
  apiServer:
    extraArgs:
      - --cloud-provider=external
  controllerManager:
    extraArgs:
      - --cloud-provider=external
  dataStoreName: postgres
  deployment:
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
  addons:
    coreDNS: {}
    konnectivity:
      server:
        port: 8132
  kubelet:
    cgroupfs: systemd
    preferredAddressTypes:
      - InternalIP
      - ExternalIP
      - Hostname
  network:
    certSANs:
    - my-cluster.domain.cloud
    serviceType: LoadBalancer
    serviceAnnotations:
      loadbalancer.openstack.org/floating-network-id: __REDACTED_NETWORK_ID__
  replicas: 3
  version: 1.27.6
```

Looking at `spec.addons` section in `TenantControlPlane`, I can't see any entry for coreDNS:

```yaml
apiVersion: kamaji.clastix.io/v1alpha1
kind: TenantControlPlane
spec:
  addons:
    konnectivity:
      agent:
        image: registry.k8s.io/kas-network-proxy/proxy-agent
        version: v0.0.32
      server:
        image: registry.k8s.io/kas-network-proxy/proxy-server
        port: 8132
        version: v0.0.32
```

If I replace `coreDNS: {}` in `KamajiControlPlane` and specify a supported property, like

```yaml
spec:
  addons:
    coreDNS:
      imageTag: v1.9.2
```

I can see a matching entry in `TenantControlPlane` and coreDNS is deployed correctly.
