### ISSUE TITLE
Incorrect KamajiControlPlaneReady condition

### ISSUE THREAD

**Issue by jds9090** [clastix/cluster-api-control-plane-provider-kamaji#71]
Related to : #66 

For the first time, I missed the important fact.
- cluster controller also watches external object : https://github.com/kubernetes-sigs/cluster-api/blob/14efefeb46dbe8d0cd0f5b7d1718e00ec58fc079/internal/controllers/cluster/cluster_controller_phases.go#L96

I could check that cluster and kamaji control plane are inheriting the readiness from Kamaji.

But I think the kamajiControlPlane condition is not correct. It is always true during my test.

Steps to reproduce
- deploy cluster by CAPI kamaji
- delete deployment(control plane)
```
ubuntu@kamaji:~$ k delete deploy kamajicontrolplane-27
deployment.apps "kamajicontrolplane-27" deleted
```
- check tenant control plane's status : Ready -> NotReady
```
kubectl get tcp -o=jsonpath={.items[0].status.kubernetesResources.version.status}
```
- check kamaji control plane's status : true -> false
```
kubectl get kamajicontrolplane -o=jsonpath={.items[0].status.ready}
```

- check kamaji control plane condition's KamajiControlPlaneReady : true -> true (not correct)
```
kubectl get kamajicontrolplane -o=jsonpath='{.items[0].status.conditions[4].type} {.items[0].status.conditions[4].status}'
```

- check cluster's status : true -> false
```
kubectl get cluster -o=jsonpath={.items[0].status.controlPlaneReady}
```

about 50 seconds later 
- deployment(control plane) : Running
- check tenant control plane's status : NotReady -> Ready
```
kubectl get tcp -o=jsonpath={.items[0].status.kubernetesResources.version.status}
```
- check kamaji control plane's status : false -> true
```
kubectl get kamajicontrolplane -o=jsonpath={.items[0].status.ready}
```

- check kamaji control plane condition's KamajiControlPlaneReady : true -> true (not correct)
```
kubectl get kamajicontrolplane -o=jsonpath='{.items[0].status.conditions[4].type} {.items[0].status.conditions[4].status}'
```

- check cluster's status : false -> true
```
kubectl get cluster -o=jsonpath={.items[0].status.controlPlaneReady}
```

  

Additionally, 

What still makes me confused is as below(@prometherion shared [this](https://github.com/clastix/cluster-api-control-plane-provider-kamaji/pull/69)). 
```
# REDACTED
status:
  conditions:
  ...
  - lastTransitionTime: "2023-12-11T16:59:16Z"
    message: TenantControlPlane in Provisioning status, enqueue back
    observedGeneration: 1
    reason: Failed
    status: "False" #  KamajiControlPlaneIsReady condition is not ready
    type: KamajiControlPlaneIsReady
  externalManagedControlPlane: true
  initialized: true
  ready: true # KamajiControlPlane's status is ready
  readyReplicas: 2
  replicas: 2
  selector: cluster.x-k8s.io/cluster-name=capi-quickstart
  unavailableReplicas: 0
  updatedReplicas: 2
  version: v1.23.10
```

When KamajiControlPlane's status is ready, KamajiControlPlaneIsReady condition is not ready.

When can this situation happen?

Please, describe this situation :) @prometherion

**Comment by prometherion** [comment]
I tried to replicate your issue @jds9090 but with no luck.

By deleting the Deployment, the KamajiControlPlane is marked as non ready:

```
$: kubectl delete deployment capi-quickstart-kubevirt
deployment.apps "capi-quickstart-kubevirt" deleted

$: kubectl get kamajicontrolplane capi-quickstart-kubevirt -o='jsonpath={.status.ready}'
false
```

Also the condition seems reporting the correct status along with the error.
```yaml
  - lastTransitionTime: "2023-12-28T16:13:30Z"
    message: TenantControlPlane in NotReady status, enqueue back
    observedGeneration: 1
    reason: Failed
    status: "False"
    type: KamajiControlPlaneIsReady
```

Once the Deployment is created back, everything's ok.

```
$: kubectl get capi-quickstart-kubevirt
NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
capi-quickstart-kubevirt   2/2     2            2           113s

$: kubectl get kamajicontrolplane capi-quickstart-kubevirt -o='jsonpath={.status.ready}'
true
```

```yaml
  - lastTransitionTime: "2023-12-28T16:14:56Z"
    message: ""
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: KamajiControlPlaneIsReady
```
